name: Glassboard
description: Know who you're sharing with.

url: http://www.glassboard.com
auto: true
permalink: /:year/:month/:title
exclude: [server, misc]
plugins:     ./_source/_plugins
source:      ./_source
destination: ./website
