name: Glassboard
description: Know who you're sharing with.

url: http://www.glassboard.com
permalink: /:year/:month/:title
exclude: [server, misc]
plugins:     _source/_plugins
source:      _source
destination: website

sass:
    sass_dir: css
    style: :compressed

